version: !!str 3.9
services:
    phpmyadmin:
            image: phpmyadmin:5.1.1
            container_name : pma
            ports:
             - 80:80
            environment:
             - "PMA_ARBITRARY=1"
            depends_on:
             - mysql
            restart: unless-stopped
            networks:
             - edge
             - db
    mysql:
            image: mysql:8.0.25
            container_name: mysql
            env_file: .mysqlenv
            restart: unless-stopped
            volumes: 
             - /opt/mysql:/var/lib/mysql
            networks:
             - db
networks:
   db:
   edge:
     external: true
           
